name: Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore          

      - name: Build
        run: dotnet build ./Mindbox.WorkingCalendar.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore
